### ISSUE TITLE
Brush Knob German Keyboard

### ISSUE THREAD

**Issue by Heinrichbreit** [kmwtr/BrushKnob#1]
I have Brush Knob connected to my Mac with German keyboard layout. The button worked immediately, but the knob did not work. Then I have found that it works, if I change the keyboard assignment in English.

This is very uncomfortable. Is there a solution to this problem?

 The knob produce with German keyboard layout üüü¨¨¨ instead [[[[[]]]]]]].

Thanks for an answer: heinrich.breiter@me.com

**Comment by vincewlkr** [comment]
I have the same problem with french keyboard.

**Comment by Kalkoon2000** [comment]
I got the same probleme as @vincewlkr , I'm gonna try to make a version for french Azerty keyboard i'll keep you in touch

**Comment by triptykon** [comment]
I'm also using a German keyboard and noticed this problem right away. Besides that I would like to use the BrushKnob for other applications and not all of them allow me to configure keyboard shortcuts for adapting functions to BrushKnob keys.

I did some research and tried to find software that allows me to remap keys from a specific keyboard to other keys. Most available software is capable of remapping certain keys to other keys, but this applies to all connected keyboards. I don't want to remap my 'ü' and '+' to '[' and ']' for my main keyboard...

I found out about a programming interface titled "Interception". It can be found at http://www.oblita.com/interception.html
Then I found a tutorial on a forum explaining how to remap certain keys on certain keyboards. It is located at http://orbiter-forum.com/showthread.php?t=30829

I haven't tried it yet, but it sounds promising. I'm not sure, when I will find the time to follow the tutorial using BrushKnob. So if any of you guys wants to give it a try, let us know if it works for you and how easy it was from your perspective. Finally it would be great to have some piece of software that allows me to activate different key-assignments (mappings) for different purposes (different applications). That would make BrushKnob a real killer tool - and that btw. was my intention from the start.

I hope that helps making some progress. I really love the BrushKnow as a cool looking device and it feels quite worthy and of high quality. Great job so far. Now let's see, how to make it more usable and working with all sorts of keyboard language settings (and other applications). ;-)

**Comment by kmwtr** [comment]
Everyone

Thank you for using BrushKnob! 
As you have confirmed, BrushKnob has only two models that US (QWERTY) and JP (JIS) signals type. I'm going straight to the point, there are two ways to solve this problem. However, both of which are a bit difficult.

**First:** Change PC / Mac settings.

In this case, you should be use the special software (or change the registry file on Windows).

**Second:** Rewrite the firmware of BrushKnob's microcomputer (AVR ATtiny85).

If you have knowledge of AVR or Arduino, it can be realized by changing the code of this file.
https://github.com/kmwtr/BrushKnob/blob/master/firmware/main.c
(It is near line 40)

Do you know what the scan code (key code) corresponds to '[' and ']' on German (QWERTZ) and French (AZERTY) keyboard? If you know, could you tell me that? I'll update the firmware on GitHub.

@triptykon 
Thank you for your very helpful information and advice. I'm considering the concept and spec for the next version of BrushKnob.

Thank you.

**Comment by Heinrichbreit** [comment]
Hello

The Key Code of the [ ] Buttons in (Swiss)German and French are combinations with the ALT-Key. Maybe that will not work for Photoshop, because the ALT-Key changes the brush tool to the Eyedropper tool.

In any case, I would make a warning for buyers of Brushknob outside the English and Japanese language zone. This way you can avoid frustration.




Freundliche Grüsse:


Heinrich Breiter
ibl und partner AG
Weissensteinstrasse 5
CH-4502 Solothurn
Telefon ++41(0)32 624 47 10
Telefax ++41(0)32 624 47 44
Mail heinrich.breiter@ibl.ch
