### ISSUE TITLE
BrushKnob not recognized

### ISSUE THREAD

**Issue by rkiesler** [kmwtr/BrushKnob#3]
Hi!

I've tried writing this also as a comment at IndieGogo, but haven't received a response, so I'm trying my luck here.

I have received the "BrushKnob" a while ago but it doesn't work at all. When I connect the BrushKnob to my PC, it just tells me, that the USB device has not been recognized, so I can't use it.

I'm running Windows 7 Pro. Please help!

Thanks.

**Comment by kmwtr** [comment]
Hi, kiesler

Have you also commented on indiegogo site? Sorry for my late reply.
Would you talk with the mail or comment field of the indiegogo campaign?

Thanks.
