### ISSUE TITLE
BrushKnob reprogrammed!

### ISSUE THREAD

**Issue by mdecaria** [kmwtr/BrushKnob#4]
Hey

Could you tell me which ISP through holes represent which pins on the ATtiny85?

ISP
Hole1 Hole2
Hole3 Hole4
Hole5 Hole6
PWR
Hole7 Hole8

So for example Hole7 is pin 4 on the ATtiny85

- Michael

**Comment by mdecaria** [comment]
![img_20170116_2147067](https://cloud.githubusercontent.com/assets/13725056/21982651/7f38ae02-dc41-11e6-922d-ad97ed00f51d.jpg)

Managed to reprogram the brushknob!!!

Was going to use the ISP outputs but got a 8 pin IC clip to attach directly to the microcontroller.

I used an Arduino UNO (clone) as the ISP programmer

Compiled the the files and flashed it, thanks for the open source code

**Comment by kmwtr** [comment]
Sorry for my late reply.
Pinout is as follows.

(Top view)
[ ISP ]
1:GND    2:RST
3:MOSI    4:SCK
5:VCC    6:MISO
[ PWR ]
GND    VIN

Thank you both!
